services:
  db:
    image: postgres:16
    container_name: easydoc_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: easydoc
    ports:
      - "5433:5432"
    volumes:
      - easydoc_pgdata:/var/lib/postgresql/data

volumes:
  easydoc_pgdata:
